// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrashToRewardsV2.Models;

#nullable disable

namespace TrashToRewardsV2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrashToRewardsV2.Models.ADMIN", b =>
                {
                    b.Property<int>("MaAD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAD"));

                    b.Property<string>("EmailAD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenAD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhauAD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDTAD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaAD");

                    b.ToTable("ADMIN");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.CTKHOQUA", b =>
                {
                    b.Property<int>("MaKQ")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaQua")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("SoLuongTrongKho")
                        .HasColumnType("int");

                    b.HasKey("MaKQ", "MaQua");

                    b.HasIndex("MaQua");

                    b.ToTable("CTKHOQUA");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.CTPHIEUDOIQUA", b =>
                {
                    b.Property<int>("MaPDQ")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaQua")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<float>("SoDiemCan")
                        .HasColumnType("real");

                    b.Property<int>("SoLuongDoi")
                        .HasColumnType("int");

                    b.HasKey("MaPDQ", "MaQua");

                    b.HasIndex("MaQua");

                    b.ToTable("CTPHIEUDOIQUA");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.CTPHIEUGHINHAN", b =>
                {
                    b.Property<int>("MaLoaiPL")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaPhieuGN")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<float>("KhoiLuongGN")
                        .HasColumnType("real");

                    b.Property<float>("SoDiemNhanDuocGN")
                        .HasColumnType("real");

                    b.HasKey("MaLoaiPL", "MaPhieuGN");

                    b.HasIndex("MaPhieuGN");

                    b.ToTable("CTPHIEUGHINHAN");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.CTPHIEUTHUGOM", b =>
                {
                    b.Property<int>("MaLoaiPL")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaPhieu")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<float>("KhoiLuong")
                        .HasColumnType("real");

                    b.Property<float>("SoDiemNhanDuoc")
                        .HasColumnType("real");

                    b.HasKey("MaLoaiPL", "MaPhieu");

                    b.HasIndex("MaPhieu");

                    b.ToTable("CTPHIEUTHUGOM");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.DONVITHUGOM", b =>
                {
                    b.Property<int>("MaDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDV"));

                    b.Property<string>("DiaChiDV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDTDV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDV");

                    b.ToTable("DONVITHUGOM");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.KHOQUA", b =>
                {
                    b.Property<int>("MaKQ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKQ"));

                    b.Property<string>("DiaChiKQ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDTKQ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKQ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKQ");

                    b.ToTable("KHOQUA");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.LICHSUTICHDIEM", b =>
                {
                    b.Property<int>("MaLS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLS"));

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaND")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGioCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<float>("SoDiemThayDoi")
                        .HasColumnType("real");

                    b.HasKey("MaLS");

                    b.HasIndex("MaND");

                    b.ToTable("LICHSUTICHDIEM");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.LOAIPHELIEU", b =>
                {
                    b.Property<int>("MaLoaiPL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiPL"));

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TiLeDiem")
                        .HasColumnType("real");

                    b.HasKey("MaLoaiPL");

                    b.ToTable("LOAIPHELIEU");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.NGUOIDUNG", b =>
                {
                    b.Property<int>("MaND")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaND"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("DiemTichLuy")
                        .HasColumnType("real");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaND");

                    b.ToTable("NGUOIDUNG");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.NHANVIEN", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("EmailNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDV")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDTNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaDV");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.NHANVIENGQ", b =>
                {
                    b.Property<int>("MaNVGQ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNVGQ"));

                    b.Property<string>("EmailNVGQ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNVGQ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaKQ")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauNVGQ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDTNVGQ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNVGQ");

                    b.HasIndex("MaKQ");

                    b.ToTable("NHANVIENGQ");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.PHANTHUONG", b =>
                {
                    b.Property<int>("MaQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQua"));

                    b.Property<float>("DiemDoi")
                        .HasColumnType("real");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongCon")
                        .HasColumnType("int");

                    b.Property<string>("TenQua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaQua");

                    b.ToTable("PHANTHUONG");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.PHIEUDATLICH", b =>
                {
                    b.Property<int>("MaPhieuDL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuDL"));

                    b.Property<string>("DiaDiemDL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaND")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDL")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiDL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhieuDL");

                    b.HasIndex("MaND");

                    b.ToTable("PHIEUDATLICH");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.PHIEUDOIQUA", b =>
                {
                    b.Property<int>("MaPDQ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPDQ"));

                    b.Property<string>("DiaDiemNhanQua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucNhanQua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaKQ")
                        .HasColumnType("int");

                    b.Property<int>("MaND")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGioDoi")
                        .HasColumnType("datetime2");

                    b.Property<float>("SoDiemSuDung")
                        .HasColumnType("real");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPDQ");

                    b.HasIndex("MaKQ");

                    b.HasIndex("MaND");

                    b.ToTable("PHIEUDOIQUA");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.PHIEUGHINHAN", b =>
                {
                    b.Property<int>("MaPhieuGN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuGN"));

                    b.Property<int>("MaND")
                        .HasColumnType("int");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGhiNhan")
                        .HasColumnType("datetime2");

                    b.Property<float>("TongDiemGN")
                        .HasColumnType("real");

                    b.HasKey("MaPhieuGN");

                    b.HasIndex("MaND");

                    b.HasIndex("MaNV");

                    b.ToTable("PHIEUGHINHAN");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.PHIEUTHUGOM", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"));

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<int>("MaXN")
                        .HasColumnType("int");

                    b.Property<float>("TongDiem")
                        .HasColumnType("real");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaXN")
                        .IsUnique();

                    b.ToTable("PHIEUTHUGOM");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.THONGBAOND", b =>
                {
                    b.Property<int>("MaTBND")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTBND"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<int>("MaND")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTaoND")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTBND");

                    b.HasIndex("MaND");

                    b.ToTable("THONGBAOND");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.THONGBAONV", b =>
                {
                    b.Property<int>("MaTBNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTBNV"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTaoNV")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTBNV");

                    b.HasIndex("MaNV");

                    b.ToTable("THONGBAONV");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.THONGBAONVGQ", b =>
                {
                    b.Property<int>("MaTBNVGQ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTBNVGQ"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<int>("MaNVGQ")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTaoNVGQ")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungNVGQ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTBNVGQ");

                    b.HasIndex("MaNVGQ");

                    b.ToTable("THONGBAONVGQ");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.XACNHAN", b =>
                {
                    b.Property<int>("MaXN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXN"));

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<int>("MaPhieuDL")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayXN")
                        .HasColumnType("datetime2");

                    b.HasKey("MaXN");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaPhieuDL")
                        .IsUnique();

                    b.ToTable("XACNHAN");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.CTKHOQUA", b =>
                {
                    b.HasOne("TrashToRewardsV2.Models.KHOQUA", "KHOQUA")
                        .WithMany("CTKHOQUAs")
                        .HasForeignKey("MaKQ")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrashToRewardsV2.Models.PHANTHUONG", "PHANTHUONG")
                        .WithMany("CTKHOQUAs")
                        .HasForeignKey("MaQua")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KHOQUA");

                    b.Navigation("PHANTHUONG");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.CTPHIEUDOIQUA", b =>
                {
                    b.HasOne("TrashToRewardsV2.Models.PHIEUDOIQUA", "PHIEUDOIQUA")
                        .WithMany("CTPHIEUDOIQUAs")
                        .HasForeignKey("MaPDQ")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrashToRewardsV2.Models.PHANTHUONG", "PHANTHUONG")
                        .WithMany("CTPHIEUDOIQUAs")
                        .HasForeignKey("MaQua")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PHANTHUONG");

                    b.Navigation("PHIEUDOIQUA");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.CTPHIEUGHINHAN", b =>
                {
                    b.HasOne("TrashToRewardsV2.Models.LOAIPHELIEU", "LOAIPHELIEU")
                        .WithMany("CTPHIEUGHINHANs")
                        .HasForeignKey("MaLoaiPL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrashToRewardsV2.Models.PHIEUGHINHAN", "PHIEUGHINHAN")
                        .WithMany("CTPHIEUGHINHANs")
                        .HasForeignKey("MaPhieuGN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LOAIPHELIEU");

                    b.Navigation("PHIEUGHINHAN");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.CTPHIEUTHUGOM", b =>
                {
                    b.HasOne("TrashToRewardsV2.Models.LOAIPHELIEU", "LOAIPHELIEU")
                        .WithMany("CTPHIEUTHUGOMs")
                        .HasForeignKey("MaLoaiPL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrashToRewardsV2.Models.PHIEUTHUGOM", "PHIEUTHUGOM")
                        .WithMany("CTPHIEUTHUGOMs")
                        .HasForeignKey("MaPhieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LOAIPHELIEU");

                    b.Navigation("PHIEUTHUGOM");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.LICHSUTICHDIEM", b =>
                {
                    b.HasOne("TrashToRewardsV2.Models.NGUOIDUNG", "NGUOIDUNG")
                        .WithMany("LICHSUTICHDIEMs")
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NGUOIDUNG");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.NHANVIEN", b =>
                {
                    b.HasOne("TrashToRewardsV2.Models.DONVITHUGOM", "DONVITHUGOM")
                        .WithMany("NHANVIENs")
                        .HasForeignKey("MaDV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DONVITHUGOM");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.NHANVIENGQ", b =>
                {
                    b.HasOne("TrashToRewardsV2.Models.KHOQUA", "KHOQUA")
                        .WithMany("NHANVIENGQs")
                        .HasForeignKey("MaKQ")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KHOQUA");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.PHIEUDATLICH", b =>
                {
                    b.HasOne("TrashToRewardsV2.Models.NGUOIDUNG", "NGUOIDUNG")
                        .WithMany("PHIEUDATLICHs")
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NGUOIDUNG");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.PHIEUDOIQUA", b =>
                {
                    b.HasOne("TrashToRewardsV2.Models.KHOQUA", "KHOQUA")
                        .WithMany()
                        .HasForeignKey("MaKQ")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrashToRewardsV2.Models.NGUOIDUNG", "NGUOIDUNG")
                        .WithMany("PHIEUDOIQUAs")
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KHOQUA");

                    b.Navigation("NGUOIDUNG");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.PHIEUGHINHAN", b =>
                {
                    b.HasOne("TrashToRewardsV2.Models.NGUOIDUNG", "NGUOIDUNG")
                        .WithMany("PHIEUGHINHANs")
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrashToRewardsV2.Models.NHANVIEN", "NHANVIEN")
                        .WithMany("PHIEUGHINHANs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NGUOIDUNG");

                    b.Navigation("NHANVIEN");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.PHIEUTHUGOM", b =>
                {
                    b.HasOne("TrashToRewardsV2.Models.NHANVIEN", "NHANVIEN")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrashToRewardsV2.Models.XACNHAN", "XACNHAN")
                        .WithOne("PhieuThuGomLienKet")
                        .HasForeignKey("TrashToRewardsV2.Models.PHIEUTHUGOM", "MaXN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NHANVIEN");

                    b.Navigation("XACNHAN");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.THONGBAOND", b =>
                {
                    b.HasOne("TrashToRewardsV2.Models.NGUOIDUNG", "NGUOIDUNG")
                        .WithMany("THONGBAONDs")
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NGUOIDUNG");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.THONGBAONV", b =>
                {
                    b.HasOne("TrashToRewardsV2.Models.NHANVIEN", "NHANVIEN")
                        .WithMany("THONGBAONVs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NHANVIEN");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.THONGBAONVGQ", b =>
                {
                    b.HasOne("TrashToRewardsV2.Models.NHANVIENGQ", "NHANVIENGQ")
                        .WithMany("THONGBAONVGQs")
                        .HasForeignKey("MaNVGQ")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NHANVIENGQ");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.XACNHAN", b =>
                {
                    b.HasOne("TrashToRewardsV2.Models.NHANVIEN", "NHANVIEN")
                        .WithMany("XACNHANs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrashToRewardsV2.Models.PHIEUDATLICH", "PHIEUDATLICH")
                        .WithOne("XACNHAN")
                        .HasForeignKey("TrashToRewardsV2.Models.XACNHAN", "MaPhieuDL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NHANVIEN");

                    b.Navigation("PHIEUDATLICH");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.DONVITHUGOM", b =>
                {
                    b.Navigation("NHANVIENs");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.KHOQUA", b =>
                {
                    b.Navigation("CTKHOQUAs");

                    b.Navigation("NHANVIENGQs");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.LOAIPHELIEU", b =>
                {
                    b.Navigation("CTPHIEUGHINHANs");

                    b.Navigation("CTPHIEUTHUGOMs");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.NGUOIDUNG", b =>
                {
                    b.Navigation("LICHSUTICHDIEMs");

                    b.Navigation("PHIEUDATLICHs");

                    b.Navigation("PHIEUDOIQUAs");

                    b.Navigation("PHIEUGHINHANs");

                    b.Navigation("THONGBAONDs");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.NHANVIEN", b =>
                {
                    b.Navigation("PHIEUGHINHANs");

                    b.Navigation("THONGBAONVs");

                    b.Navigation("XACNHANs");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.NHANVIENGQ", b =>
                {
                    b.Navigation("THONGBAONVGQs");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.PHANTHUONG", b =>
                {
                    b.Navigation("CTKHOQUAs");

                    b.Navigation("CTPHIEUDOIQUAs");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.PHIEUDATLICH", b =>
                {
                    b.Navigation("XACNHAN")
                        .IsRequired();
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.PHIEUDOIQUA", b =>
                {
                    b.Navigation("CTPHIEUDOIQUAs");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.PHIEUGHINHAN", b =>
                {
                    b.Navigation("CTPHIEUGHINHANs");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.PHIEUTHUGOM", b =>
                {
                    b.Navigation("CTPHIEUTHUGOMs");
                });

            modelBuilder.Entity("TrashToRewardsV2.Models.XACNHAN", b =>
                {
                    b.Navigation("PhieuThuGomLienKet")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
